<a href="https://colab.research.google.com/github/rahiraja22/RE_CT_project/blob/main/RE_CT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import zipfile

# Extract the uploaded zip file
with zipfile.ZipFile("HR_dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("HR_dataset")

In [2]:
import pandas as pd
import glob

# Path
all_files = glob.glob("HR_dataset/HR_dataset/*.csv")

print("Total CSV files found:", len(all_files))

# Read with encoding fallback
dfs = []
for f in all_files:
    try:
        df_temp = pd.read_csv(f, encoding='utf-8')
    except UnicodeDecodeError:
        df_temp = pd.read_csv(f, encoding='latin-1')  # fallback encoding
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

print(df.shape)
print(df.head())

Total CSV files found: 23
(195145, 25)
  State Code District Code      India/States Division Group  Class  \
0        `13          `000  STATE - NAGALAND      `00  `000  `0000
1        `13          `000  STATE - NAGALAND      `01  `000  `0000
2        `13          `000  STATE - NAGALAND      `01  `011  `0000
3        `13          `000  STATE - NAGALAND      `01  `011  `0111
4        `13          `000  STATE - NAGALAND      `01  `011  `0112

                                            NIC Name  \
0                                              Total
1  Crop and animal production, hunting and relate...
2                     Growing of non-perennial crops
3  Growing of cereals (except rice), leguminous c...
4                                    Growing of rice

   Main Workers - Total -  Persons  Main Workers - Total - Males  \
0                           206397                        140493
1                             9250                          4557
2                             1065                           521
3                               13                             8
4                              769                           390

   Main Workers - Total - Females  ...  Main Workers - Urban - Females  \
0                           65904  ...                           32500
1                            4693  ...                            1831
2                             544  ...                             227
3                               5  ...                               1
4                             379  ...                             169

   Marginal Workers - Total -  Persons  Marginal Workers - Total - Males  \
0                                62665                             27824
1                                 6960                              2565
2                                  921                               293
3                                   13                                 9
4                                  435                               190

   Marginal Workers - Total - Females  Marginal Workers - Rural -  Persons  \
0                               34841                                43865
1                                4395                                 4991
2                                 628                                  612
3                                   4                                    9
4                                 245                                  264

   Marginal Workers - Rural - Males  Marginal Workers - Rural - Females  \
0                             20384                               23481
1                              2130                                2861
2                               210                                 402
3                                 6                                   3
4                               125                                 139

   Marginal Workers - Urban -  Persons  Marginal Workers - Urban - Males  \
0                                18800                              7440
1                                 1969                               435
2                                  309                                83
3                                    4                                 3
4                                  171                                65

   Marginal Workers - Urban - Females
0                               11360
1                                1534
2                                 226
3                                   1
4                                 106

[5 rows x 25 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195145 entries, 0 to 195144
Data columns (total 25 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   State Code                           195145 non-null  object
 1   District Code                        195145 non-null  object
 2   India/States                         195145 non-null  object
 3   Division                             195145 non-null  object
 4   Group                                195145 non-null  object
 5   Class                                195145 non-null  object
 6   NIC Name                             195145 non-null  object
 7   Main Workers - Total -  Persons      195145 non-null  int64
 8   Main Workers - Total - Males         195145 non-null  int64
 9   Main Workers - Total - Females       195145 non-null  int64
 10  Main Workers - Rural -  Persons      195145 non-null  int64
 11  Main Workers - Rural - Males         195145 non-null  int64
 12  Main Workers - Rural - Females       195145 non-null  int64
 13  Main Workers - Urban -  Persons      195145 non-null  int64
 14  Main Workers - Urban - Males         195145 non-null  int64
 15  Main Workers - Urban - Females       195145 non-null  int64
 16  Marginal Workers - Total -  Persons  195145 non-null  int64
 17  Marginal Workers - Total - Males     195145 non-null  int64
 18  Marginal Workers - Total - Females   195145 non-null  int64
 19  Marginal Workers - Rural -  Persons  195145 non-null  int64
 20  Marginal Workers - Rural - Males     195145 non-null  int64
 21  Marginal Workers - Rural - Females   195145 non-null  int64
 22  Marginal Workers - Urban -  Persons  195145 non-null  int64
 23  Marginal Workers - Urban - Males     195145 non-null  int64
 24  Marginal Workers - Urban - Females   195145 non-null  int64
dtypes: int64(18), object(7)
memory usage: 37.2+ MB

In [4]:
df = df.applymap(lambda x: str(x).replace("`", "") if isinstance(x, str) else x)

/tmp/ipython-input-4127687953.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: str(x).replace("`", "") if isinstance(x, str) else x)

In [5]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("-", "_")

In [6]:
num_cols = df.columns.drop(["india/states", "nic_name"])
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors="coerce")

In [7]:
df.isnull().sum()

state_code                             0
district_code                          0
india/states                           0
division                               0
group                                  0
class                                  0
nic_name                               0
main_workers___total____persons        0
main_workers___total___males           0
main_workers___total___females         0
main_workers___rural____persons        0
main_workers___rural___males           0
main_workers___rural___females         0
main_workers___urban____persons        0
main_workers___urban___males           0
main_workers___urban___females         0
marginal_workers___total____persons    0
marginal_workers___total___males       0
marginal_workers___total___females     0
marginal_workers___rural____persons    0
marginal_workers___rural___males       0
marginal_workers___rural___females     0
marginal_workers___urban____persons    0
marginal_workers___urban___males       0
marginal_workers___urban___females     0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

In [9]:

df["state_code"] = df["state_code"].astype(int)
df["district_code"] = df["district_code"].astype(int)

In [10]:
print(df.head())

   state_code  district_code      india/states  division  group  class  \
0          13              0  STATE - NAGALAND         0      0      0
1          13              0  STATE - NAGALAND         1      0      0
2          13              0  STATE - NAGALAND         1     11      0
3          13              0  STATE - NAGALAND         1     11    111
4          13              0  STATE - NAGALAND         1     11    112

                                            nic_name  \
0                                              Total
1  Crop and animal production, hunting and relate...
2                     Growing of non-perennial crops
3  Growing of cereals (except rice), leguminous c...
4                                    Growing of rice

   main_workers___total____persons  main_workers___total___males  \
0                           206397                        140493
1                             9250                          4557
2                             1065                           521
3                               13                             8
4                              769                           390

   main_workers___total___females  ...  main_workers___urban___females  \
0                           65904  ...                           32500
1                            4693  ...                            1831
2                             544  ...                             227
3                               5  ...                               1
4                             379  ...                             169

   marginal_workers___total____persons  marginal_workers___total___males  \
0                                62665                             27824
1                                 6960                              2565
2                                  921                               293
3                                   13                                 9
4                                  435                               190

   marginal_workers___total___females  marginal_workers___rural____persons  \
0                               34841                                43865
1                                4395                                 4991
2                                 628                                  612
3                                   4                                    9
4                                 245                                  264

   marginal_workers___rural___males  marginal_workers___rural___females  \
0                             20384                               23481
1                              2130                                2861
2                               210                                 402
3                                 6                                   3
4                               125                                 139

   marginal_workers___urban____persons  marginal_workers___urban___males  \
0                                18800                              7440
1                                 1969                               435
2                                  309                                83
3                                    4                                 3
4                                  171                                65

   marginal_workers___urban___females
0                               11360
1                                1534
2                                 226
3                                   1
4                                 106

[5 rows x 25 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195145 entries, 0 to 195144
Data columns (total 25 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   state_code                           195145 non-null  int64
 1   district_code                        195145 non-null  int64
 2   india/states                         195145 non-null  object
 3   division                             195145 non-null  int64
 4   group                                195145 non-null  int64
 5   class                                195145 non-null  int64
 6   nic_name                             195145 non-null  object
 7   main_workers___total____persons      195145 non-null  int64
 8   main_workers___total___males         195145 non-null  int64
 9   main_workers___total___females       195145 non-null  int64
 10  main_workers___rural____persons      195145 non-null  int64
 11  main_workers___rural___males         195145 non-null  int64
 12  main_workers___rural___females       195145 non-null  int64
 13  main_workers___urban____persons      195145 non-null  int64
 14  main_workers___urban___males         195145 non-null  int64
 15  main_workers___urban___females       195145 non-null  int64
 16  marginal_workers___total____persons  195145 non-null  int64
 17  marginal_workers___total___males     195145 non-null  int64
 18  marginal_workers___total___females   195145 non-null  int64
 19  marginal_workers___rural____persons  195145 non-null  int64
 20  marginal_workers___rural___males     195145 non-null  int64
 21  marginal_workers___rural___females   195145 non-null  int64
 22  marginal_workers___urban____persons  195145 non-null  int64
 23  marginal_workers___urban___males     195145 non-null  int64
 24  marginal_workers___urban___females   195145 non-null  int64
dtypes: int64(23), object(2)
memory usage: 37.2+ MB

In [12]:
df.describe()

,state_code,district_code,division,group,class,main_workers___total____persons,main_workers___total___males,main_workers___total___females,main_workers___rural____persons,main_workers___rural___males,...,main_workers___urban___females,marginal_workers___total____persons,marginal_workers___total___males,marginal_workers___total___females,marginal_workers___rural____persons,marginal_workers___rural___males,marginal_workers___rural___females,marginal_workers___urban____persons,marginal_workers___urban___males,marginal_workers___urban___females
count,195145.000000,195145.000000,195145.000000,195145.000000,195145.000000,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,...,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,195145.000000,195145.000000
mean,19.178278,332.223377,46.590351,389.422404,2293.804709,1.492138e+03,1.193171e+03,2.989664e+02,6.606187e+02,5.170353e+02,...,1.553830e+02,3.642672e+02,1.826322e+02,1.816350e+02,2.502286e+02,1.165241e+02,1.337045e+02,1.140386e+02,66.108094,47.930472
std,9.057612,196.176206,28.800311,313.186034,3059.131669,4.568169e+04,3.773917e+04,8.582019e+03,2.044436e+04,1.654295e+04,...,4.531593e+03,1.176940e+04,5.760575e+03,6.309699e+03,8.232274e+03,3.723078e+03,4.748460e+03,3.842889e+03,2132.581727,1803.271234
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,10.000000,153.000000,23.000000,103.000000,0.000000,6.000000e+00,6.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
50%,19.000000,332.000000,46.000000,370.000000,113.000000,2.800000e+01,2.300000e+01,3.000000e+00,1.200000e+01,8.000000e+00,...,0.000000e+00,4.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
75%,27.000000,516.000000,70.000000,631.000000,4659.000000,1.880000e+02,1.450000e+02,2.400000e+01,7.400000e+01,5.600000e+01,...,1.200000e+01,2.800000e+01,1.800000e+01,6.000000e+00,1.400000e+01,8.000000e+00,3.000000e+00,9.000000e+00,6.000000,2.000000
max,34.000000,637.000000,99.000000,992.000000,9920.000000,1.561976e+07,1.280140e+07,2.818356e+06,6.770444e+06,5.446541e+06,...,1.494453e+06,3.834122e+06,1.966750e+06,1.867372e+06,2.515182e+06,1.223824e+06,1.291358e+06,1.318940e+06,742926.000000,576014.000000

In [13]:
print(df["india/states"].unique())
print(df["nic_name"].nunique())

['STATE - NAGALAND' 'District - Mon' 'District - Mokokchung'
 'District - Zunheboto' 'District - Wokha' 'District - Dimapur'
 'District - Phek' 'District - Tuensang' 'District - Longleng'
 'District - Kiphire' 'District - Kohima' 'District - Peren'
 'STATE - KERALA' 'District - Kasaragod' 'District - Kannur'
 'District - Wayanad' 'District - Kozhikode' 'District - Malappuram'
 'District - Palakkad' 'District - Thrissur' 'District - Ernakulam'
 'District - Idukki' 'District - Kottayam' 'District - Alappuzha'
 'District - Pathanamthitta' 'District - Kollam'
 'District - Thiruvananthapuram' 'STATE - MANIPUR' 'District - Senapati'
 'District - Tamenglong' 'District - Churachandpur' 'District - Bishnupur'
 'District - Thoubal' 'District - Imphal West' 'District - Imphal East'
 'District - Ukhrul' 'District - Chandel' 'STATE - MIZORAM'
 'District - Mamit' 'District - Kolasib' 'District - Aizawl'
 'District - Champhai' 'District - Serchhip' 'District - Lunglei'
 'District - Lawngtlai' 'District - Saiha' 'STATE - RAJASTHAN'
 'District - Ganganagar' 'District - Hanumangarh' 'District - Bikaner'
 'District - Churu' 'District - Jhunjhunun' 'District - Alwar'
 'District - Bharatpur' 'District - Dhaulpur' 'District - Karauli'
 'District - Sawai Madhopur' 'District - Dausa' 'District - Jaipur'
 'District - Sikar' 'District - Nagaur' 'District - Jodhpur'
 'District - Jaisalmer' 'District - Barmer' 'District - Jalor'
 'District - Sirohi' 'District - Pali' 'District - Ajmer'
 'District - Tonk' 'District - Bundi' 'District - Bhilwara'
 'District - Rajsamand' 'District - Dungarpur' 'District - Banswara'
 'District - Chittaurgarh' 'District - Kota' 'District - Baran'
 'District - Jhalawar' 'District - Udaipur' 'District - Pratapgarh'
 'STATE - NCT OF DELHI' 'District - North West' 'District - North'
 'District - North East' 'District - East' 'District - New Delhi'
 'District - Central' 'District - West' 'District - South West'
 'District - South' 'STATE - TAMIL NADU' 'District - Thiruvallur'
 'District - Chennai' 'District - Kancheepuram' 'District - Vellore'
 'District - Tiruvannamalai' 'District - Viluppuram' 'District - Salem'
 'District - Namakkal' 'District - Erode' 'District - The Nilgiris'
 'District - Dindigul' 'District - Karur' 'District - Tiruchirappalli'
 'District - Perambalur' 'District - Ariyalur' 'District - Cuddalore'
 'District - Nagapattinam' 'District - Thiruvarur' 'District - Thanjavur'
 'District - Pudukkottai' 'District - Sivaganga' 'District - Madurai'
 'District - Theni' 'District - Virudhunagar' 'District - Ramanathapuram'
 'District - Thoothukkudi' 'District - Tirunelveli'
 'District - Kanniyakumari' 'District - Dharmapuri'
 'District - Krishnagiri' 'District - Coimbatore' 'District - Tiruppur'
 'STATE - MAHARASHTRA' 'District - Nandurbar' 'District - Dhule'
 'District - Jalgaon' 'District - Buldana' 'District - Akola'
 'District - Washim' 'District - Amravati' 'District - Wardha'
 'District - Nagpur' 'District - Bhandara' 'District - Gondiya'
 'District - Gadchiroli' 'District - Chandrapur' 'District - Yavatmal'
 'District - Nanded' 'District - Hingoli' 'District - Parbhani'
 'District - Jalna' 'District - Aurangabad' 'District - Nashik'
 'District - Thane' 'District - Mumbai Suburban' 'District - Mumbai'
 'District - Raigarh' 'District - Pune' 'District - Ahmadnagar'
 'District - Bid' 'District - Latur' 'District - Osmanabad'
 'District - Solapur' 'District - Satara' 'District - Ratnagiri'
 'District - Sindhudurg' 'District - Kolhapur' 'District - Sangli'
 'STATE - ARUNACHAL PRADESH' 'District - Tawang' 'District - West Kameng'
 'District - East Kameng' 'District - Papum Pare'
 'District - Upper Subansiri' 'District - West Siang'
 'District - East Siang' 'District - Upper Siang' 'District - Changlang'
 'District - Tirap' 'District - Lower Subansiri' 'District - Kurung Kumey'
 'District - Dibang Valley' 'District - Lower Dibang Valley'
 'District - Lohit' 'District - Anjaw' 'STATE - SIKKIM'
 'District - North  District' 'District - West District'
 'District - South District' 'District - East District' 'STATE - TRIPURA'
 'District - West Tripura' 'District - South Tripura' 'District - Dhalai'
 'District - North Tripura' 'STATE - HIMACHAL PRADESH' 'District - Chamba'
 'District - Kangra' 'District - Lahul & Spiti' 'District - Kullu'
 'District - Mandi' 'District - Hamirpur' 'District - Una'
 'District - Bilaspur' 'District - Solan' 'District - Sirmaur'
 'District - Shimla' 'District - Kinnaur' 'STATE - KARNATAKA'
 'District - Belgaum' 'District - Bagalkot' 'District - Bijapur'
 'District - Bidar' 'District - Raichur' 'District - Koppal'
 'District - Gadag' 'District - Dharwad' 'District - Uttara Kannada'
 'District - Haveri' 'District - Bellary' 'District - Chitradurga'
 'District - Davanagere' 'District - Shimoga' 'District - Udupi'
 'District - Chikmagalur' 'District - Tumkur' 'District - Bangalore'
 'District - Mandya' 'District - Hassan' 'District - Dakshina Kannada'
 'District - Kodagu' 'District - Mysore' 'District - Chamarajanagar'
 'District - Gulbarga' 'District - Yadgir' 'District - Kolar'
 'District - Chikkaballapura' 'District - Bangalore Rural'
 'District - Ramanagara' 'STATE - GUJARAT' 'District - Kachchh'
 'District - Banas Kantha' 'District - Patan' 'District - Mahesana'
 'District - Sabar Kantha' 'District - Gandhinagar' 'District - Ahmadabad'
 'District - Surendranagar' 'District - Rajkot' 'District - Jamnagar'
 'District - Porbandar' 'District - Junagadh' 'District - Amreli'
 'District - Bhavnagar' 'District - Anand' 'District - Kheda'
 'District - Panch Mahals' 'District - Dohad' 'District - Vadodara'
 'District - Narmada' 'District - Bharuch' 'District - The Dangs'
 'District - Navsari' 'District - Valsad' 'District - Surat'
 'District - Tapi' 'STATE - ODISHA' 'District - Bargarh'
 'District - Jharsuguda' 'District - Sambalpur' 'District - Debagarh'
 'District - Sundargarh' 'District - Kendujhar' 'District - Mayurbhanj'
 'District - Baleshwar' 'District - Bhadrak' 'District - Kendrapara'
 'District - Jagatsinghapur' 'District - Cuttack' 'District - Jajapur'
 'District - Dhenkanal' 'District - Anugul' 'District - Nayagarh'
 'District - Khordha' 'District - Puri' 'District - Ganjam'
 'District - Gajapati' 'District - Kandhamal' 'District - Baudh'
 'District - Subarnapur' 'District - Balangir' 'District - Nuapada'
 'District - Kalahandi' 'District - Rayagada' 'District - Nabarangapur'
 'District - Koraput' 'District - Malkangiri' 'STATE - ASSAM'
 'District - Kokrajhar' 'District - Dhubri' 'District - Goalpara'
 'District - Barpeta' 'District - Morigaon' 'District - Nagaon'
 'District - Sonitpur' 'District - Lakhimpur' 'District - Dhemaji'
 'District - Tinsukia' 'District - Dibrugarh' 'District - Sivasagar'
 'District - Jorhat' 'District - Golaghat' 'District - Karbi Anglong'
 'District - Dima Hasao' 'District - Cachar' 'District - Karimganj'
 'District - Hailakandi' 'District - Bongaigaon' 'District - Chirang'
 'District - Kamrup' 'District - Kamrup Metropolitan' 'District - Nalbari'
 'District - Baksa' 'District - Darrang' 'District - Udalguri'
 'STATE - UTTARAKHAND' 'District - Uttarkashi' 'District - Chamoli'
 'District - Rudraprayag' 'District - Tehri Garhwal' 'District - Dehradun'
 'District - Garhwal' 'District - Pithoragarh' 'District - Bageshwar'
 'District - Almora' 'District - Champawat' 'District - Nainital'
 'District - Udham Singh Nagar' 'District - Hardwar' 'STATE - BIHAR'
 'District - Pashchim Champaran' 'District - Purba Champaran'
 'District - Sheohar' 'District - Sitamarhi' 'District - Madhubani'
 'District - Supaul' 'District - Araria' 'District - Kishanganj'
 'District - Purnia' 'District - Katihar' 'District - Madhepura'
 'District - Saharsa' 'District - Darbhanga' 'District - Muzaffarpur'
 'District - Gopalganj' 'District - Siwan' 'District - Saran'
 'District - Vaishali' 'District - Samastipur' 'District - Begusarai'
 'District - Khagaria' 'District - Bhagalpur' 'District - Banka'
 'District - Munger' 'District - Lakhisarai' 'District - Sheikhpura'
 'District - Nalanda' 'District - Patna' 'District - Bhojpur'
 'District - Buxar' 'District - Kaimur (Bhabua)' 'District - Rohtas'
 'District - Gaya' 'District - Nawada' 'District - Jamui'
 'District - Jehanabad' 'District - Arwal' 'STATE - PUDUCHERRY'
 'District - Yanam' 'District - Puducherry' 'District - Mahe'
 'District - Karaikal' 'STATE - WEST BENGAL' 'District - Darjiling'
 'District - Jalpaiguri' 'District - Koch Bihar'
 'District - Uttar Dinajpur' 'District - Dakshin Dinajpur'
 'District - Maldah' 'District - Murshidabad' 'District - Birbhum'
 'District - Barddhaman' 'District - Nadia'
 'District - North Twenty Four Parganas' 'District - Hugli'
 'District - Bankura' 'District - Puruliya' 'District - Haora'
 'District - Kolkata' 'District - South Twenty Four Parganas'
 'District - Paschim Medinipur' 'District - Purba Medinipur'
 'STATE - UTTAR PRADESH' 'District - Saharanpur'
 'District - Muzaffarnagar' 'District - Bijnor' 'District - Moradabad'
 'District - Rampur' 'District - Jyotiba Phule Nagar' 'District - Meerut'
 'District - Baghpat' 'District - Ghaziabad'
 'District - Gautam Buddha Nagar' 'District - Bulandshahr'
 'District - Aligarh' 'District - Mahamaya Nagar' 'District - Mathura'
 'District - Agra' 'District - Firozabad' 'District - Mainpuri'
 'District - Budaun' 'District - Bareilly' 'District - Pilibhit'
 'District - Shahjahanpur' 'District - Kheri' 'District - Sitapur'
 'District - Hardoi' 'District - Unnao' 'District - Lucknow'
 'District - Rae Bareli' 'District - Farrukhabad' 'District - Kannauj'
 'District - Etawah' 'District - Auraiya' 'District - Kanpur Dehat'
 'District - Kanpur Nagar' 'District - Jalaun' 'District - Jhansi'
 'District - Lalitpur' 'District - Mahoba' 'District - Banda'
 'District - Chitrakoot' 'District - Fatehpur' 'District - Kaushambi'
 'District - Allahabad' 'District - Bara Banki' 'District - Faizabad'
 'District - Ambedkar Nagar' 'District - Sultanpur' 'District - Bahraich'
 'District - Shrawasti' 'District - Balrampur' 'District - Gonda'
 'District - Siddharthnagar' 'District - Basti'
 'District - Sant Kabir Nagar' 'District - Mahrajganj'
 'District - Gorakhpur' 'District - Kushinagar' 'District - Deoria'
 'District - Azamgarh' 'District - Mau' 'District - Ballia'
 'District - Jaunpur' 'District - Ghazipur' 'District - Chandauli'
 'District - Varanasi' 'District - Sant Ravidas Nagar (Bhadohi)'
 'District - Mirzapur' 'District - Sonbhadra' 'District - Etah'
 'District - Kanshiram Nagar' 'STATE - JHARKHAND' 'District - Garhwa'
 'District - Chatra' 'District - Kodarma' 'District - Giridih'
 'District - Deoghar' 'District - Godda' 'District - Sahibganj'
 'District - Pakur' 'District - Dhanbad' 'District - Bokaro'
 'District - Lohardaga' 'District - Purbi Singhbhum' 'District - Palamu'
 'District - Latehar' 'District - Hazaribagh' 'District - Ramgarh'
 'District - Dumka' 'District - Jamtara' 'District - Ranchi'
 'District - Khunti' 'District - Gumla' 'District - Simdega'
 'District - Pashchimi Singhbhum' 'District - Saraikela-Kharsawan'
 'STATE - GOA' 'District - North Goa' 'District - South Goa']
587

In [14]:
df.to_csv("clean_hr_data.csv", index=False)

In [55]:
pip install pyngrok

Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (7.3.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.2)

In [62]:
!pip install streamlit==1.29.0 pyngrok --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 68.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 29.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 64.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.7/44.7 kB 3.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
db-dtypes 1.4.3 requires packaging>=24.2.0, but you have packaging 23.2 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.25.8 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
ydf 0.13.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 4.25.8 which is incompatible.
xarray 2025.9.0 requires packaging>=24.1, but you have packaging 23.2 which is incompatible.
google-cloud-bigquery 3.36.0 requires packaging>=24.2.0, but you have packaging 23.2 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.

In [1]:
!pip install streamlit pyngrok scikit-learn pandas

Collecting streamlit
  Downloading streamlit-1.49.1-py3-none-any.whl.metadata (9.5 kB)
Collecting pyngrok
  Downloading pyngrok-7.3.0-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.4.2)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.3.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2025.8.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.27.1)
Downloading streamlit-1.49.1-py3-none-any.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 58.5 MB/s eta 0:00:00
Downloading pyngrok-7.3.0-py3-none-any.whl (25 kB)
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 111.2 MB/s eta 0:00:00
Installing collected packages: pyngrok, pydeck, streamlit
Successfully installed pydeck-0.9.1 pyngrok-7.3.0 streamlit-1.49.1

In [2]:
from pyngrok import ngrok

ngrok.set_auth_token("32FCSTcjwg8WjeyCXUpFnPChsDa_6gHM7sSHvwYJSRquiKnQ6")

In [7]:
%%writefile hr_app.py
import streamlit as st
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# 1. Load data
# -----------------------------
st.set_page_config(page_title="Workers EDA Dashboard", layout="wide")

st.title("📊 Workers Industrial Classification - EDA Dashboard")

df = pd.read_csv("clean_hr_data.csv")

# Define numeric cols globally
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

# -----------------------------
# 2. Pre-compute Aggregates
# -----------------------------

# Total by State
state_total = df.groupby("india/states")[
    ["main_workers___total____persons",
     "marginal_workers___total____persons"]
].sum().reset_index()
state_total["total_workers"] = (
    state_total["main_workers___total____persons"]
    + state_total["marginal_workers___total____persons"]
)

# Total by Industry
industry_total = df.groupby("nic_name")[
    ["main_workers___total____persons",
     "marginal_workers___total____persons"]
].sum().reset_index()
industry_total["total_workers"] = (
    industry_total["main_workers___total____persons"]
    + industry_total["marginal_workers___total____persons"]
)

# State + Industry
state_industry_agg = df.groupby(["india/states", "nic_name"])[
    ["main_workers___total____persons", "marginal_workers___total____persons"]
].sum().reset_index()
state_industry_agg["total_workers"] = (
    state_industry_agg["main_workers___total____persons"]
    + state_industry_agg["marginal_workers___total____persons"]
)

# Male vs Female by State
gender_state = df.groupby("india/states")[
    ["main_workers___total___males", "main_workers___total___females",
     "marginal_workers___total___males", "marginal_workers___total___females"]
].sum().reset_index()
gender_state["male_workers"] = (
    gender_state["main_workers___total___males"] + gender_state["marginal_workers___total___males"]
)
gender_state["female_workers"] = (
    gender_state["main_workers___total___females"] + gender_state["marginal_workers___total___females"]
)

# Rural vs Urban
rural_urban = df.groupby("india/states")[
    ["main_workers___rural____persons", "main_workers___urban____persons",
     "marginal_workers___rural____persons", "marginal_workers___urban____persons"]
].sum().reset_index()
rural_urban["rural_workers"] = (
    rural_urban["main_workers___rural____persons"] + rural_urban["marginal_workers___rural____persons"]
)
rural_urban["urban_workers"] = (
    rural_urban["main_workers___urban____persons"] + rural_urban["marginal_workers___urban____persons"]
)

# -----------------------------
# 3. Sidebar Controls
# -----------------------------
st.sidebar.header("🔎 Select EDA View")
eda_option = st.sidebar.selectbox(
    "Choose a Visualization",
    [
        "Overall Stats",
        "Top States by Workers",
        "Top Industries",
        "Gender Analysis",
        "Rural vs Urban",
        "Heatmap / Correlation",
        "Distribution Histogram",
        "Outliers Detection"
    ]
)

# -----------------------------
# 4. Visualization Sections
# -----------------------------

if eda_option == "Overall Stats":
    st.subheader("📌 Overall Workers Statistics")
    total_workers = (
        df["main_workers___total____persons"].sum()
        + df["marginal_workers___total____persons"].sum()
    )
    main_workers = df["main_workers___total____persons"].sum()
    marginal_workers = df["marginal_workers___total____persons"].sum()
    male_total = (
        df["main_workers___total___males"].sum()
        + df["marginal_workers___total___males"].sum()
    )
    female_total = (
        df["main_workers___total___females"].sum()
        + df["marginal_workers___total___females"].sum()
    )

    st.metric("Total Workers", f"{total_workers:,}")
    st.metric("Main Workers", f"{main_workers:,}")
    st.metric("Marginal Workers", f"{marginal_workers:,}")
    st.metric("Male Workers", f"{male_total:,}")
    st.metric("Female Workers", f"{female_total:,}")

elif eda_option == "Top States by Workers":
    st.subheader("🏆 Top States by Total Workers")
    top_n = st.sidebar.slider("Select Top N States", 5, 20, 10)
    top_states = state_total.sort_values("total_workers", ascending=False).head(top_n)
    fig = px.bar(top_states, x="india/states", y="total_workers",
                 title=f"Top {top_n} States by Total Workers")
    st.plotly_chart(fig, use_container_width=True)

elif eda_option == "Top Industries":
    st.subheader("🏭 Top Industries by Workers")
    top_n = st.sidebar.slider("Select Top N Industries", 5, 20, 10)
    top_industries = industry_total.sort_values("total_workers", ascending=False).head(top_n)
    fig = px.bar(top_industries, x="nic_name", y="total_workers",
                 title=f"Top {top_n} Industries by Workers")
    st.plotly_chart(fig, use_container_width=True)

elif eda_option == "Gender Analysis":
        st.subheader("👩‍🦱 vs 👨 Gender Split")
        gender_totals = {
            "Males": df["main_workers___total___males"].sum(),
            "Females": df["main_workers___total___females"].sum()
        }
        fig = px.bar(x=list(gender_totals.keys()), y=list(gender_totals.values()),
                     title="Overall Gender Split", text_auto=True)
        st.plotly_chart(fig, use_container_width=True)


elif eda_option == "Rural vs Urban":
    st.subheader("🏠 Rural vs 🌆 Urban")
    rural_urban_totals = {
        "Rural": df["main_workers___rural____persons"].sum() + df["marginal_workers___rural____persons"].sum(),
        "Urban": df["main_workers___urban____persons"].sum() + df["marginal_workers___urban____persons"].sum()
    }
    fig = px.pie(names=list(rural_urban_totals.keys()), values=list(rural_urban_totals.values()),
                 title="Rural vs Urban Workers")
    st.plotly_chart(fig, use_container_width=True)


elif eda_option == "Heatmap / Correlation":
    st.subheader("🔥 Correlation Heatmap")
    corr = df[numeric_cols].corr()
    fig, ax = plt.subplots(figsize=(15, 10))
    sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5, ax=ax)
    st.pyplot(fig)

elif eda_option == "Distribution Histogram":
    st.subheader("📈 Distribution of Numeric Columns")
    selected_col = st.sidebar.selectbox("Choose numeric column:", numeric_cols)
    fig = px.histogram(df, x=selected_col, nbins=50,
                       title=f"Histogram of {selected_col}", marginal="box")
    st.plotly_chart(fig, use_container_width=True)


elif eda_option == "Outliers Detection":
    st.subheader("📦 Outlier Detection Across All Numeric Columns")

    # numeric columns automatically detect
    numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

    import matplotlib.pyplot as plt
    import seaborn as sns

    fig, ax = plt.subplots(figsize=(15, 8))
    sns.boxplot(data=df[numeric_cols], orient="h", ax=ax, palette="Set2", fliersize=4)
    ax.set_title("Boxplots of All Numeric Columns", fontsize=16)
    st.pyplot(fig)

Overwriting hr_app.py

In [7]:
!pkill -f ngrok

In [4]:
!streamlit run hr_app.py --server.port 8501 &> logs.txt &

In [5]:
!tail -n 40 logs.txt

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.75.166.39:8501

In [6]:
public_url = ngrok.connect(8501)
print("Streamlit app URL:", public_url)

Streamlit app URL: NgrokTunnel: "https://a4a39e60975b.ngrok-free.app" -> "http://localhost:8501"